### ISSUE TITLE
Couldn't load plugin 'qgis_gee_data_catalog' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by lunar-studio** [sandroklippel/qgis_gee_data_catalog#10]
Receiving this error when starting.

ModuleNotFoundError: No module named 'ee' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_gee_data_catalog\__init__.py", line 33, in classFactory
    from .qgis_gee_data_catalog import GeeDataCatalog
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/l...AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_gee_data_catalog\qgis_gee_data_catalog.py", line 26, in 
    from .ee_interface import (add_ee_image_layer, download_ee_image_layer,
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_gee_data_catalog\ee_interface.py", line 6, in 
    import ee
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'ee'

**Comment by lunar-studio** [comment]
nevermind I think I just solved it lol. Should have read your instructions better.

**Comment by scameto** [comment]
hi, I have this error, can you help me? tanks

**Comment by sandroklippel** [comment]
Sorry for the poor documentation. Can you try the instructions in
Portuguese from this link?
Instalacao · sandroklippel/qgis_gee_data_catalog Wiki · GitHub
<https://github.com/sandroklippel/qgis_gee_data_catalog/wiki/Instalacao>

Em ter., 16 de jan. de 2024 às 18:54, Santiago Gaston Cameto Hernandez <
***@***.***> escreveu:
