### ISSUE TITLE
ModuleNotFoundError: No module named 'ee' 

### ISSUE THREAD

**Issue by openstudio-one** [sandroklippel/qgis_gee_data_catalog#12]
Goodmorning,

Every time I run QGIS, I encounter the following error (popup) - "Failed to load plugin 'qgis_gee_data_catalog' due to error calling classFactory() method"

**ModuleNotFoundError: No module named 'ee'** 
```
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_gee_data_catalog/__init__.py", line 33, in classFactory
    from .qgis_gee_data_catalog import GeeDataCatalog
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_gee_data_catalog/qgis_gee_data_catalog.py", line 26, in 
    from .ee_interface import (add_ee_image_layer, download_ee_image_layer,
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_gee_data_catalog/ee_interface.py", line 6, in 
    import ee
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'ee'
```

Versione Python: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
Versione di QGIS: 3.32.3-Lima Lima, 67d46100b5b

**Comment by sandroklippel** [comment]
Hi,

EE Python API (earthengine-api) must be installed, and it is required a
Google Earth Engine account, besides authenticate it.

Windows (OSGeo4W Shell):

> python -m pip install --upgrade pip
> python -m pip install earthengine-api --user

Linux (Ubuntu based):

$ sudo apt update
$ sudo apt upgrade
$ sudo apt install python3-pip
$ pip3 install earthengine-api --user

To authenticate on python prompt (python/python3):

>>> import ee
>>> ee.Authenticate(auth_mode='notebook')

Follow this link for a tutorial:
Instalacao · sandroklippel/qgis_gee_data_catalog Wiki (github.com)
<https://github.com/sandroklippel/qgis_gee_data_catalog/wiki/Instalacao>


Em qua., 8 de mai. de 2024 às 07:56, openstudio-one <
***@***.***> escreveu:
