### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'ee'


### ISSUE THREAD

**Issue by joel-uribe** [sandroklippel/qgis_gee_data_catalog#7]
No se pudo cargar el complemento 'qgis_gee_data_catalog' debido a un error al llamar a su método classFactory()
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/joel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_gee_data_catalog/__init__.py", line 33, in classFactory
    from .qgis_gee_data_catalog import GeeDataCatalog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/joel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_gee_data_catalog/qgis_gee_data_catalog.py", line 26, in <module>
    from .ee_interface import (add_ee_image_layer, download_ee_image_layer,
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/joel/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_gee_data_catalog/ee_interface.py", line 6, in <module>
    import ee
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'ee'

```
qgis_gee_data_catalog 0.4.2, QGIS 3.10.4-A Coruña on Linux 5.13.0-30-generic

**Comment by Diego635** [comment]
It seems you need to download the plugin google earth engine too.
then it works.

THIS SHOULD BE MENTIONED IN THE PLUGIN!!!

**Comment by sandroklippel** [comment]
REAME.md updated.
